spring:
  datasource:
    url: jdbc:h2:file:${user.home}/ClubeDosSargentos/data/banco;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: false   # 🔥 MUITO IMPORTANTE
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never   # 🔥 NÃO EXECUTA data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080